name: CI - Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Check code formatting with black
        run: |
          black --check --diff .

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Syntax check
        run: |
          python -m py_compile main.py

      - name: Validate response format
        run: |
          python tests/validate_format.py

      - name: Run unit tests
        run: |
          python tests/simple_test.py

      - name: Run integration tests
        run: |
          python tests/test_chillmcp.py

      - name: Verify CLI parameters
        run: |
          python main.py --help
          # Test with custom parameters (should start and be killable)
          timeout 3 python main.py --boss_alertness 50 --boss_alertness_cooldown 10 || true
